### PR TITLE
Improve backward compatibility

### PR DESCRIPTION
**Pull request by Mihaiii**
For https://github.com/Palindrom/palindrom-redirect/issues/1#issuecomment-343150114 .

Sorry for the ugly code. I don't know how to check better than this.

@tomalec , @alshakero , please review.

### CODE REVIEW

**Comment by alshakero** [comment]
That's a good idea! Maybe doing this is cleaner, DRYer, and a tad faster?

```js
this.dispatchEvent(
  new CustomEvent(
    `${this.getAttribute('is')}-pushstate`,
    {
      "detail":{"url":url},
      "bubbles": true
    }
  )
);
```
_Side note: it would cool if you to assign me as a reviewier when you'd like me to review, to utilize most of github's functionality (filtering, search etcc...) ;)_

**Comment by Mihaiii** [comment]
Yup, that's much better. I made the commit, please check. :)

**Comment by Mihaiii** [comment]
> Side note: it would cool if you to assign me as a reviewier when you'd like me to review, to utilize most of github's functionality (filtering, search etcc...) ;)

I can't in this case, but I will do so when possible. The thing is that I don't know who would have some time to review so I tend to tag multiple people, instead of requesting review from multiple persons and then not being sure if I should wait for review from everybody or not before merge. :)

**Comment by alshakero** [comment]
Good point :/

**Comment by alshakero** [comment]
I’ll check one more thing when I’m home.

**Review by alshakero — APPROVED** [review]
Checked event handlers in `palindrom-dom` to make sure having unmatched names (eg. `palindrom-client` and `puppet-redirect`) wouldn't break things.

LGTM

**Comment by Mihaiii** [comment]
👍 
I can't merge it. Please merge it if there isn't anything else.

**Comment by alshakero** [comment]
@Mihaiii sorry for that, Palindrom org is full to add you. I'll ask someone who doesn't need to be here (there are many) to give you their place.

**Pull request merged**
